import '@mantine/core/styles.css'
import '@mantine/notifications/styles.css'
import './globals.css'

import type { Metadata } from 'next'

import QueryClientProviderWrapper from '@/components/QueryClientProviderWrapper'
import { ColorSchemeScript, MantineProvider } from '@mantine/core'
import { Notifications } from '@mantine/notifications'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <head>
        <ColorSchemeScript />
      </head>
      <body>
        <MantineProvider>
          <Notifications />
          <QueryClientProviderWrapper>{children}</QueryClientProviderWrapper>
        </MantineProvider>
      </body>
    </html>
  )
}
